# relative line numbers
add-highlighter global/ number-lines -relative -hlcursor
#add-highlighter global/ wrap

#adding the pugin manager
source "%val{config}/plugins/plug.kak/rc/plug.kak"

#adding powerline
plug "jdugan6240/powerline.kak" config %{
        powerline-start
}
#adding search highlighter
plug "alexherbo2/search-highlighter.kak"
plug "listentolist/kakoune-table" domain "gitlab.com" config %{
# suggested mappings
# map global user t ": evaluate-commands -draft table-align<ret>" -docstring "align table"
# map global user t ": table-enable<ret>" -docstring "enable table mode"
# map global user T ": table-disable<ret>" -docstring "disable table mode"
# map global user t ": table-toggle<ret>" -docstring "toggle table mode"
# map global user t ": enter-user-mode table<ret>" -docstring "table"
# map global user T ": enter-user-mode -lock table<ret>" -docstring "table (lock)"
                                 }
