source ~/.zplug/init.zsh

#self-update the package
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

#Fish-like history search
zplug "zsh-users/zsh-history-substring-search"

#syntax-highlighting
zplug "zsh-users/zsh-syntax-highlighting"

#colorising output of programs
zplug "zpm-zsh/colorize", use:colorize.plugin.zsh, from:github, as:plugin

#locally sourcing autosuggest
zplug "zsh-users/zsh-autosuggestions", use:zsh-autosuggestions.plugin.zsh, from:github, as:plugin

#add fzf for history
zplug "joshskidmore/zsh-fzf-history-search", use:zsh-fzf-history-search.zsh, from:github, as:plugin
#zsh-theme
#zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme

#asynchronous support
zplug "mafredri/zsh-async", from:github, use:async.zsh
#colorise man pages
zplug "plugins/colored-man-pages", from:oh-my-zsh
#aliases
alias ls='exa --git --group-directories-first --time-style=long-iso'
alias l='ls -lbF'
alias la='ls -la'
#alias llm='ll --sort=modified'
alias ll='ls -lbhHigUmuSa'
#alias lx='ls -lbhHigUmuSa@'
#alias tree='exa -RT'
alias ex="exa --git --long "
alias exa="exa -all"

#zsh-history setting
#zsh-history setting
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
#setting up auto-cd
setopt  autocd autopushd
#delete key
bindkey "^[[3~" delete-char
#loading the modules
zplug load 

#rust starship prompt
eval "$(starship init zsh)"

#exporting cargo binaries
export PATH=$PATH:/home/zero/.cargo/bin
export CHROME_EXECUTABLE=/snap/bin/chromium
export PATH=$PATH:/home/zero/bin/flutter/bin:/home/zero/.local/bin:/home/zero/.local/share/gem/ruby/3.0.0/bin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
